### ISSUE TITLE
build failed in python3.12

### ISSUE THREAD

**Issue by GreyRaphael** [RealistikDash/kcp.py#35]
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '-fno-strict-overflow', '-Wsign-compare', '-DDYNAMIC_ANNOTATIONS_ENABLED=1', '-DNDEBUG', '-fcf-protection', '-fexceptions', '-fcf-protection', '-fexceptions', '-fcf-protection', '-fexceptions', '-O3', '-fPIC', '-Ikcp', '-I/home/xxx/envs/jupy12/include', '-I/usr/include/python3.12', '-c', 'kcp/extension.c', '-o', 'build/temp.linux-x86_64-cpython-312/kcp/extension.o']' returned non-zero exit status 1.

**Comment by RealistikDash** [comment]
Apologies for the delay (GitHub notifications are a bit sus). Should be fixed as of `0.1.5`. This has now been uploaded to Pypi.

**Comment by RealistikDash** [comment]
Wheels published under 0.1.6 as well
![image](https://github.com/user-attachments/assets/c98bea03-07fd-461f-8e97-17cf98b1af91)
